spring:
  datasource:
    url: jdbc:sqlite:${MINICLAW_DB_PATH:./miniclaw.db}
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
      connection-init-sql: "PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL;"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    locations: classpath:db/migration-sqlite

memory:
  embedding:
    provider: none
